### PR TITLE
v0.4.9

### PR DESCRIPTION
**Pull request by hariadi**
- 3742876 Remove unused module
- 21eb780 Load package with require
- 6dc316a Update template structure
- 3fa8f63 Duplicate with installDependencies

### CODE REVIEW

**Comment by doowb** [comment]
I like how you're referencing the commits for each version.

**Comment by hariadi** [comment]
Haha. That's what I'm doing:
1. Just setup alias `gl='git log --graph --pretty=format:'\''%Cgreen%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr)%Creset'\'' --abbrev-commit --date=relative'`
2. after push, merge and creating tag, remote update to get new tag
3. `gl newtag..develop`

**Comment by jonschlinkert** [comment]
Yeah I think you do a great job with these, @hariadi

**Comment by doowb** [comment]
@StevenBlack the [node.js docs on modules](http://nodejs.org/api/modules.html) have a lot of information but don't specify anything about how you can load json files. I'm not sure where I first learned that could be done, but it works.

**Comment by doowb** [comment]
NVM... they do talk about different file types [here](http://nodejs.org/api/modules.html#modules_file_modules)

**Comment by StevenBlack** [comment]
Thanks @doowb this is very helpful.

**Pull request merged**
