### PR TITLE
NPM repo is permalinks not assemble-contrib-permalinks / Links pointing to wrong directory

### PR DESCRIPTION
**Pull request by MylesBorins**
While the github repo is called "assemble-contrib-permalinks", the npm package is simply named "permalinks".  As such when yeoman generates the package.json and attempts to run npm install everything asplodes.

This single change seemed to fix that problem for me.

As well there is a commit fixing a problem in the header where links are pointing to the wrong place.

### CODE REVIEW

**Comment by MylesBorins** [comment]
It looks like this was broken in #22

**Comment by jonschlinkert** [comment]
Really everything explodes? I'm guessing that's due to some magic that's happening in Yeoman, since github forwards URLs and git endpoints when you change the name of a repo. I haven't had any issues with what you're describing. Of course it's good to update this, but that problem shouldn't be happening.

**Comment by MylesBorins** [comment]
it's npm specifically that it is break

```
$ npm install assemble-contrib-permalinks
npm http GET https://registry.npmjs.org/assemble-contrib-permalinks
npm http 404 https://registry.npmjs.org/assemble-contrib-permalinks
npm ERR! 404 'assemble-contrib-permalinks' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Darwin 12.5.0
npm ERR! command "/usr/local/Cellar/node/0.10.22/bin/node" "/usr/local/bin/npm" "install" "assemble-contrib-permalinks"
npm ERR! cwd /Users/thealphanerd/github
npm ERR! node -v v0.10.22
npm ERR! npm -v 1.3.14
npm ERR! code E404
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/thealphanerd/github/npm-debug.log
npm ERR! not ok code 0
```

**Comment by jonschlinkert** [comment]
Wait, I misunderstood.  I'm doing that a lot tonight lol, I better get some sleep... Thanks for fixing this!

**Comment by MylesBorins** [comment]
No problem… I'm looking forward to digging in to assemble a bit more.  Let me know if you need help with upstream dev.

Cheers,

Myles

**Comment by jonschlinkert** [comment]
@TheAlphaNerd awesome, glad to hear it!  We can always use help with dev, what do you like working on? we're about to start refactoring for 0.5.0 after next week, so I'm sure we'll have lots of things we can use help on. cc @doowb

**Comment by MylesBorins** [comment]
I've been playing quite a bit with grunt / yeoman... so I could probably help with that.  Do you currently have any yeoman scaffolding for stuff such as making new blog items or new pages?

**Comment by jonschlinkert** [comment]
@hariadi is the man you'll want to talk to about that. we can always use help with managing boilerplates too. let me know anytime if you have any questions, I'll try to make sure you get the answers you need.

**Comment by hariadi** [comment]
Thanks @TheAlphaNerd 

You can look Assemble [scaffold here](https://github.com/assemble/generator-assemble/tree/master/app/templates)

Currently generator-assemble only support handlebarjs engine. We need help with #9 if you have time to look.

**Pull request merged**
